language: ruby
dist: trusty
osx_image: xcode9.3
os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.7.0
  - 2.6.0
  - 2.5.0
  - 2.4.0
  - jruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-3
jobs:
  exclude:
    - os: osx
      rvm: rbx-3
    - os: osx
      rvm: ruby-head
    - os: osx
      rvm: jruby-head
before_install: gem install bundler -v 1.15.0
